### ISSUE TITLE
Module 6, 8, and 11 Labs - Missing images

### ISSUE THREAD

**Issue by MarkA21** [arm-education/Rapid-Embedded-Education-Kit#11]
In section 3.1 of the module 6 lab there is a missing image.

In section 3.1 of the module 8 lab there is a missing image.

In section 3.1 of module 11 lab there is a missing image.

Think these are all referring to the pull up GPIO image. Can we try to resolve this.

**Comment by ozzwozz** [comment]
I think I had changed file names without realising, I have made a PR with the changes

**Comment by MarkA21** [comment]
Resolved.
